# Generated by Django 5.2 on 2025-05-14 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojistas', '0002_alter_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
