# Generated by Django 5.2 on 2025-05-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojistas', '0003_alter_estoque_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sugerida', models.IntegerField()),
                ('data_previsao', models.DateField(auto_now_add=True)),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojistas.lojista')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojistas.produto')),
            ],
        ),
    ]
