# Generated by Django 5.2 on 2025-05-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaopedido',
            name='texto_resumo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
